import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import { ThemeProvider } from "@/components/theme-provider";
import Header from "@/components/header";
import Footer from "@/components/footer";
import { ScrollProvider } from "@/contexts/scroll-context";

const clashGrotesk = localFont({
  src: [
    {
      path: "./fonts/ClashGrotesk-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/ClashGrotesk-Medium.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "./fonts/ClashGrotesk-Semibold.woff2",
      weight: "600",
      style: "normal",
    },
    {
      path: "./fonts/ClashGrotesk-Bold.woff2",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-clashgrotesk",
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export const metadata: Metadata = {
  title: "Build With Tomo",
  description: "Web development, data, and more!",
  icons: {
    icon: [
      { url: "/icon-16.png", sizes: "16x16", type: "image/png" }, // 16x16 icon
      { url: "/icon-32.png", sizes: "32x32", type: "image/png" }, // 32x32 icon
      { url: "/icon-192.png", sizes: "192x192", type: "image/png" }, // 192x192 icon
    ],
    shortcut: "/icon-32.png", //  use the 32x32 icon as the shortcut icon
    apple: [
      { url: "/icon-180.png", sizes: "180x180", type: "image/png" }, // Apple touch icon
    ],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`relative !scroll-smooth pt-24 font-sans sm:pt-32 ${clashGrotesk.variable}`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <ScrollProvider>
            <Header />
            {children}
            <Footer />
          </ScrollProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
